name: Code Format Check

on:
  push:
    branches:
      - main
      - release*
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./FootballApi
      
    - name: Check formatting
      run: dotnet format --verify-no-changes
      working-directory: ./FootballApi
